Neos:
  Flow:
    mvc:
      routes:
        # Override this to false to not add the SEO routes.
        'Neos.Seo':
          variables:
            # Override this to change the uri to the sitemap
            xmlSitemapPath: 'sitemap.xml'
  Neos:
    fusion:
      autoInclude:
        'Neos.Seo': true

    userInterface:
      translation:
        autoInclude:
          'Neos.Seo': ['NodeTypes/*']

  Seo:
    # robots.txt settings
    robotsTxt:
      dimensionsPresets: null
    # Twitter Card settings
    twitterCard:
      # the Twitter handle for the twitter:site attribution
      siteHandle: ~
    # Facebook settings
    facebook:
      # The id of the user that can be followed on this site
      profileId: ''
      # List of facebook user ids of your pages/apps administrators
      admins: []
      # List of facebook channel ids of your pages
      pages: []
    # Social profile for the structured data object
    socialProfile:
      # `type` can be either `Person` or `Organization`
      type: Person
      # `logo` can be for example `resource://Vendor.Site/Public/Images/MyLogo.png`
      logo: ''
      profiles:
        twitter: ~
        facebook: ~
        instagram: ~
        linkedIn: ~
        youTube: ~

  Media:
    thumbnailPresets:
      'Neos.Seo:OpenGraph':
        maximumWidth: 1200
        maximumHeight: 630
      'Neos.Seo:TwitterCard.SummaryCardLargeImage':
        maximumWidth: 1200
        maximumHeight: 600
      'Neos.Seo:TwitterCard.SummaryCard':
        maximumWidth: 600
        maximumHeight: 600

